### ISSUE TITLE
not able to create account

### ISSUE THREAD

**Issue by laredo** [cool-pot/AI-Driven-Chatting-Service#1]
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>chatbox-cloudcomputing</BucketName><RequestId>CF59895388E862EC</RequestId><HostId>EXIvuzT/pUOsP/I923muVblI/DuR7HFKiAcqX7COYrLp4R5dbLp4lu42KnFaEZhdAon/Y5JCc5Y=</HostId></Error>

**Comment by cool-pot** [comment]
Sorry, I have shut down this service since the AWS bills is a considerable cost for me as a student. The code repo here is just code archives now.
